### ISSUE TITLE
Found a unobfuscated version.

### ISSUE THREAD

**Issue by LocalsGitHub** [Stanley-GF/QRCode-Grabber#3]
The repo below is the very same thing that this repos does except nothing is obfuscated. cheers!
https://github.com/D0wzyx/QRCode-Grabber

**Comment by iamnotgoodcoder** [comment]
This is actually untrue, You are just bad!

**Comment by LocalsGitHub** [comment]
?

**Comment by Stanley-GF** [comment]
that really useful issue. Old version was unobfuscated, this guy just copy the code. I will push non-obfuscate version :)

**Comment by LocalsGitHub** [comment]
kk
